### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'dont_upcast_attention'

### ISSUE THREAD

**Issue by wujm424606** [logtd/ComfyUI-FLATTEN#4]
![image](https://github.com/logtd/ComfyUI-FLATTEN/assets/38379474/1c3cdc70-3a13-4a0b-a3b3-448910cd6fd0)

**Comment by logtd** [comment]
Hello, please update to the most recent version of FLATTEN to resolve this issue.

Thanks!
